/****** Object:  Table [dbo].[USER_LOGIN_HISTORY]    Script Date: 05/23/2013 09:52:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_LOGIN_HISTORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_LOGIN] [nvarchar](250) NOT NULL,
	[USER_NAME] [nvarchar](250) NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_USER_LOGIN_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[USER_LOGIN_HISTORY] ADD  CONSTRAINT [DF_USER_LOGIN_HISTORY_TIMESTAMP]  DEFAULT (getdate()) FOR [TIMESTAMP]
GO


