//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esynctraining.AdobeConnect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Esynctraining.AdobeConnect.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the number of meeting hosts for your Adobe Connect account.  Please consider adding additional meeting hosts or remove meeting hosts that are inactive..
        /// </summary>
        public static string AdobeConnectMeetingHostQuota {
            get {
                return ResourceManager.GetString("AdobeConnectMeetingHostQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save user information in database. Please contact system administrator..
        /// </summary>
        public static string CanSaveToDb {
            get {
                return ResourceManager.GetString("CanSaveToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email doesn&apos;t exist.
        /// </summary>
        public static string CantCreatePrincipalWithEmptyEmail {
            get {
                return ResourceManager.GetString("CantCreatePrincipalWithEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable retrieve information about LMS users..
        /// </summary>
        public static string CantRetrieveLmsUsers {
            get {
                return ResourceManager.GetString("CantRetrieveLmsUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist in AC database. You must create AC accounts manually..
        /// </summary>
        public static string CreateAcPrincipalManually {
            get {
                return ResourceManager.GetString("CreateAcPrincipalManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. .
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is occured. Try again later or contact your administrator..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is occured. .
        /// </summary>
        public static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you provided is incorrect. Please try again..
        /// </summary>
        public static string IncorrectAcPassword {
            get {
                return ResourceManager.GetString("IncorrectAcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timed out. Please refresh the page..
        /// </summary>
        public static string SessionTimeOut {
            get {
                return ResourceManager.GetString("SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Adobe Connect user is already a participant of the meeting..
        /// </summary>
        public static string UserIsAlreadyParticipant {
            get {
                return ResourceManager.GetString("UserIsAlreadyParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist in Adobe Connect..
        /// </summary>
        public static string UserNotInAdobeConnect {
            get {
                return ResourceManager.GetString("UserNotInAdobeConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the users cannot be synchronized due to: .
        /// </summary>
        public static string UsersCannotBeSync {
            get {
                return ResourceManager.GetString("UsersCannotBeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users with duplicate email exist, .
        /// </summary>
        public static string UsersDuplicateEmail {
            get {
                return ResourceManager.GetString("UsersDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users with empty email exist, .
        /// </summary>
        public static string UsersEmptyEmail {
            get {
                return ResourceManager.GetString("UsersEmptyEmail", resourceCulture);
            }
        }
    }
}
