//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizResultServiceNamespace
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class QuizResultDTO : object
    {
        
        private string acEmailField;
        
        private int acSessionIdField;
        
        private int appInFocusTimeField;
        
        private int appMaximizedTimeField;
        
        private int companyIdField;
        
        private double dateCreatedField;
        
        private string emailField;
        
        private double endTimeField;
        
        private System.Nullable<int> eventQuizMappingIdField;
        
        private System.Guid guidField;
        
        private bool isArchiveField;
        
        private bool isCompletedField;
        
        private int lmsIdField;
        
        private int lmsUserParametersIdField;
        
        private string participantNameField;
        
        private int quizIdField;
        
        private int quizResultIdField;
        
        private int scoreField;
        
        private double startTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acEmail
        {
            get
            {
                return this.acEmailField;
            }
            set
            {
                this.acEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int acSessionId
        {
            get
            {
                return this.acSessionIdField;
            }
            set
            {
                this.acSessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int appInFocusTime
        {
            get
            {
                return this.appInFocusTimeField;
            }
            set
            {
                this.appInFocusTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int appMaximizedTime
        {
            get
            {
                return this.appMaximizedTimeField;
            }
            set
            {
                this.appMaximizedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> eventQuizMappingId
        {
            get
            {
                return this.eventQuizMappingIdField;
            }
            set
            {
                this.eventQuizMappingIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isArchive
        {
            get
            {
                return this.isArchiveField;
            }
            set
            {
                this.isArchiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCompleted
        {
            get
            {
                return this.isCompletedField;
            }
            set
            {
                this.isCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lmsId
        {
            get
            {
                return this.lmsIdField;
            }
            set
            {
                this.lmsIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lmsUserParametersId
        {
            get
            {
                return this.lmsUserParametersIdField;
            }
            set
            {
                this.lmsUserParametersIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string participantName
        {
            get
            {
                return this.participantNameField;
            }
            set
            {
                this.participantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quizId
        {
            get
            {
                return this.quizIdField;
            }
            set
            {
                this.quizIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quizResultId
        {
            get
            {
                return this.quizResultIdField;
            }
            set
            {
                this.quizResultIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
    public partial class Error : object
    {
        
        private int errorCodeField;
        
        private string errorDetailField;
        
        private string errorMessageField;
        
        private string errorTypeField;
        
        private string[] faultEntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorDetail
        {
            get
            {
                return this.errorDetailField;
            }
            set
            {
                this.errorDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] faultEntities
        {
            get
            {
                return this.faultEntitiesField;
            }
            set
            {
                this.faultEntitiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultSaveAllDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class QuizResultSaveAllDTO : object
    {
        
        private string[] faultsField;
        
        private QuizResultServiceNamespace.QuizResultDTO[] savedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] faults
        {
            get
            {
                return this.faultsField;
            }
            set
            {
                this.faultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuizResultServiceNamespace.QuizResultDTO[] saved
        {
            get
            {
                return this.savedField;
            }
            set
            {
                this.savedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuizResultServiceNamespace.IQuizResultService")]
    public interface IQuizResultService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/GetAll", ReplyAction="http://tempuri.org/IQuizResultService/GetAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/GetAllErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/DeleteById", ReplyAction="http://tempuri.org/IQuizResultService/DeleteByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/DeleteByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<int> DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/GetById", ReplyAction="http://tempuri.org/IQuizResultService/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/GetByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/GetByGuid", ReplyAction="http://tempuri.org/IQuizResultService/GetByGuidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/GetByGuidErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> GetByGuidAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/Save", ReplyAction="http://tempuri.org/IQuizResultService/SaveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/SaveErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> SaveAsync(QuizResultServiceNamespace.QuizResultDTO result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultService/SaveAll", ReplyAction="http://tempuri.org/IQuizResultService/SaveAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QuizResultServiceNamespace.Error), Action="http://tempuri.org/IQuizResultService/SaveAllErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultSaveAllDTO> SaveAllAsync(QuizResultServiceNamespace.QuizResultDTO[] results);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IQuizResultServiceChannel : QuizResultServiceNamespace.IQuizResultService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class QuizResultServiceClient : System.ServiceModel.ClientBase<QuizResultServiceNamespace.IQuizResultService>, QuizResultServiceNamespace.IQuizResultService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public QuizResultServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(QuizResultServiceClient.GetBindingForEndpoint(endpointConfiguration), QuizResultServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(QuizResultServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(QuizResultServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<int> DeleteByIdAsync(int id)
        {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> GetByGuidAsync(System.Guid guid)
        {
            return base.Channel.GetByGuidAsync(guid);
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultDTO> SaveAsync(QuizResultServiceNamespace.QuizResultDTO result)
        {
            return base.Channel.SaveAsync(result);
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceNamespace.QuizResultSaveAllDTO> SaveAllAsync(QuizResultServiceNamespace.QuizResultDTO[] results)
        {
            return base.Channel.SaveAllAsync(results);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuizResultService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IQuizResultService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuizResultService))
            {
                return new System.ServiceModel.EndpointAddress("http://dev.edugamecloud.com/services/QuizResultService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IQuizResultService))
            {
                return new System.ServiceModel.EndpointAddress("http://dev.edugamecloud.com/services/QuizResultService.svc/amf");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IQuizResultService,
            
            CustomBinding_IQuizResultService,
        }
    }
}
