//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorsTexts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your company doesn&apos;t have any active license.
        /// </summary>
        internal static string AccessError_CompanyLicenseIsExpired {
            get {
                return ResourceManager.GetString("AccessError_CompanyLicenseIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string AccessError_InvalidPassword {
            get {
                return ResourceManager.GetString("AccessError_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exists with the given email..
        /// </summary>
        internal static string AccessError_NoUserExistsWithTheGivenEmail {
            get {
                return ResourceManager.GetString("AccessError_NoUserExistsWithTheGivenEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessError.
        /// </summary>
        internal static string AccessError_Subject {
            get {
                return ResourceManager.GetString("AccessError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry user is inactive and can&apos;t be logged in.
        /// </summary>
        internal static string AccessError_UserIsInactive {
            get {
                return ResourceManager.GetString("AccessError_UserIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exists with given id..
        /// </summary>
        internal static string DeleteById_NoUserExists {
            get {
                return ResourceManager.GetString("DeleteById_NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity creation error.
        /// </summary>
        internal static string EntityCreationError_Subject {
            get {
                return ResourceManager.GetString("EntityCreationError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the objects were not saved. See FaultEntities property for more details.
        /// </summary>
        internal static string EntityCreation_PartialSuccessMessage {
            get {
                return ResourceManager.GetString("EntityCreation_PartialSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityDeleteError.
        /// </summary>
        internal static string EntityDeleteError_Subject {
            get {
                return ResourceManager.GetString("EntityDeleteError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityGetError.
        /// </summary>
        internal static string EntityGetError_Subject {
            get {
                return ResourceManager.GetString("EntityGetError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        internal static string ExportError_InvalidFormat {
            get {
                return ResourceManager.GetString("ExportError_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for export or invalid smiId.
        /// </summary>
        internal static string ExportError_NoData {
            get {
                return ResourceManager.GetString("ExportError_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportError.
        /// </summary>
        internal static string ExportError_Subject {
            get {
                return ResourceManager.GetString("ExportError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exists with given id..
        /// </summary>
        internal static string GetById_NoUserExists {
            get {
                return ResourceManager.GetString("GetById_NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        internal static string GetResultError_NotFound {
            get {
                return ResourceManager.GetString("GetResultError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetResultError.
        /// </summary>
        internal static string GetResultError_Subject {
            get {
                return ResourceManager.GetString("GetResultError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUploadEnd.
        /// </summary>
        internal static string ImageUploadEnd_Subject {
            get {
                return ResourceManager.GetString("ImageUploadEnd_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded by weborb was not found..
        /// </summary>
        internal static string ImageUploadEnd_WebOrbNotFound {
            get {
                return ResourceManager.GetString("ImageUploadEnd_WebOrbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ImageUploadFailed_FileNotFound {
            get {
                return ResourceManager.GetString("ImageUploadFailed_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUploadFailed.
        /// </summary>
        internal static string ImageUploadFailed_Subject {
            get {
                return ResourceManager.GetString("ImageUploadFailed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user not found.
        /// </summary>
        internal static string ImageUploadInitialization_CurrentUserNotFound {
            get {
                return ResourceManager.GetString("ImageUploadInitialization_CurrentUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageUploadInitialization.
        /// </summary>
        internal static string ImageUploadInitialization_Subject {
            get {
                return ResourceManager.GetString("ImageUploadInitialization_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        internal static string ImportError_InvalidFormat {
            get {
                return ResourceManager.GetString("ImportError_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for import or invalid smiId.
        /// </summary>
        internal static string ImportError_NoData {
            get {
                return ResourceManager.GetString("ImportError_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string ImportError_NotFound {
            get {
                return ResourceManager.GetString("ImportError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportError.
        /// </summary>
        internal static string ImportError_Subject {
            get {
                return ResourceManager.GetString("ImportError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string ImportError_Unknown {
            get {
                return ResourceManager.GetString("ImportError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent for account activation..
        /// </summary>
        internal static string SendActivationEmailSuccess {
            get {
                return ResourceManager.GetString("SendActivationEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        internal static string SendActivationError_EmailIsInvalid {
            get {
                return ResourceManager.GetString("SendActivationError_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendActivationError.
        /// </summary>
        internal static string SendActivationError_Subject {
            get {
                return ResourceManager.GetString("SendActivationError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found.
        /// </summary>
        internal static string SessionError_NotFound {
            get {
                return ResourceManager.GetString("SessionError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSessionError.
        /// </summary>
        internal static string SessionError_Subject {
            get {
                return ResourceManager.GetString("SessionError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code expired.
        /// </summary>
        internal static string UserActivationError_ExpiredActivationCode {
            get {
                return ResourceManager.GetString("UserActivationError_ExpiredActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activation code..
        /// </summary>
        internal static string UserActivationError_InvalidActivationCode {
            get {
                return ResourceManager.GetString("UserActivationError_InvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserActivationError.
        /// </summary>
        internal static string UserActivationError_Subject {
            get {
                return ResourceManager.GetString("UserActivationError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been activated..
        /// </summary>
        internal static string UserActivationSuccess {
            get {
                return ResourceManager.GetString("UserActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists and is not activated..
        /// </summary>
        internal static string UserCreateUpdateError_NotActivated {
            get {
                return ResourceManager.GetString("UserCreateUpdateError_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;User is not activated. Use SendActivate to re-send the activation code&quot;.
        /// </summary>
        internal static string UserCreateUpdateError_NotActivated_Details {
            get {
                return ResourceManager.GetString("UserCreateUpdateError_NotActivated_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreateUpdateError.
        /// </summary>
        internal static string UserCreateUpdateError_Subject {
            get {
                return ResourceManager.GetString("UserCreateUpdateError_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists and activated..
        /// </summary>
        internal static string UserCreationError_AlreadyExists {
            get {
                return ResourceManager.GetString("UserCreationError_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered in the system..
        /// </summary>
        internal static string UserCreationError_AlreadyExists_Details {
            get {
                return ResourceManager.GetString("UserCreationError_AlreadyExists_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the limit of users. Please contact administration to upgrade your license..
        /// </summary>
        internal static string UserCreationError_LicenseError {
            get {
                return ResourceManager.GetString("UserCreationError_LicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreationError.
        /// </summary>
        internal static string UserCreationError_Subject {
            get {
                return ResourceManager.GetString("UserCreationError_Subject", resourceCulture);
            }
        }
    }
}
