//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the T4 template.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Esynctraining.Core.Domain.Entities;

namespace EdugameCloud.Lti.Domain.Entities
{
    public partial class AcCachePrincipal : Entity
    {
        public virtual int LmsCompanyId { get; set; }

        public virtual string AccountId { get; set; }

        public virtual string DisplayId { get; set; }

        public virtual string Email { get; set; }

        public virtual string FirstName { get; set; }

        public virtual System.Boolean? HasChildren { get; set; }

        public virtual System.Boolean? IsHidden { get; set; }

        public virtual System.Boolean? IsPrimary { get; set; }

        public virtual string LastName { get; set; }

        public virtual string Login { get; set; }

        public virtual string Name { get; set; }

        public virtual string PrincipalId { get; set; }

        public virtual string Type { get; set; }

	}

}
