{
	"oauth_consumer_key": "ed84943c-7320-4431-b3f7-57bbab636076",
    /*"oauth_timestamp": "1448451144",
    "oauth_signature": "qFBokE500QIAwf4iTAaiGAE1lZI=",*/
    "oauth_signature_method": "HMAC-SHA1",    
    /*"oauth_nonce": "w71C51BRTLPNaYyWXh3Y9fWU3OXX63OP1BejmCAkAzA",*/
    "oauth_version": "1.0",
    "context_id": "8b265b198342c8bf50f40e685ff7adf6bb7eb510",
    "context_label": "AT1",
    "context_title": "AutoRegression",
    "custom_canvas_api_domain": "esynctraining.instructure.com",
    "custom_canvas_course_id": "330", "custom_canvas_enrollment_state": "active",
    "custom_canvas_user_id": "1",
    "custom_canvas_user_login_id": "mike@esynctraining.com",
    "ext_roles": "urn:lti:instrole:ims/lis/Administrator,urn:lti:instrole:ims/lis/Instructor,urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Instructor,urn:lti:sysrole:ims/lis/User",
    "launch_presentation_document_target": "iframe",
    "launch_presentation_height": "400",
    "launch_presentation_locale": "en",
    "launch_presentation_return_url": "https://esynctraining.instructure.com/courses/330/external_content/success/external_tool_redirect",
    "launch_presentation_width": "800",
    "lis_person_contact_email_primary": "mike@esynctraining.com",
    "lis_person_name_family": "Kollen",
    "lis_person_name_full": "Mike Kollen",
    "lis_person_name_given": "Mike",
    "lti_message_type": "basic-lti-launch-request",
    "lti_version": "LTI-1p0",
    "oauth_callback": "about:blank",
    "resource_link_id": "8b265b198342c8bf50f40e685ff7adf6bb7eb510",
    "resource_link_title": "Adobe Connect Prod",
    "roles": "Instructor,urn:lti:instrole:ims/lis/Administrator",
    "tool_consumer_info_product_family_code": "canvas",
    "tool_consumer_info_version": "cloud",
    "tool_consumer_instance_contact_email": "notifications@instructure.com",
    "tool_consumer_instance_guid": "aebwtYfE7KMTTE1Mqga8hOZhHLLCq86OW1DURZcH:canvas-lms",
    "tool_consumer_instance_name": "eSyncTraining",
    "user_id": "0340cde37624c04979a6c3fdd0afc2479f8405ad",
    "user_image": "https://secure.gravatar.com/avatar/119609781cc74cde3c9ea20e3862c0e7?s=50\u0026d=https%3A%2F%2Fcanvas.instructure.com%2Fimages%2Fmessages%2Favatar-50.png"
}
