//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyEventsServiceNamespace
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyQuizEventMappingSaveDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO))]
    public partial class CompanyQuizEventMappingSaveDTO : object
    {
        
        private string acEventScoIdField;
        
        private int companyAcDomainIdField;
        
        private int eventQuizMappingIdField;
        
        private int postQuizIdField;
        
        private int preQuizIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acEventScoId
        {
            get
            {
                return this.acEventScoIdField;
            }
            set
            {
                this.acEventScoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyAcDomainId
        {
            get
            {
                return this.companyAcDomainIdField;
            }
            set
            {
                this.companyAcDomainIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int eventQuizMappingId
        {
            get
            {
                return this.eventQuizMappingIdField;
            }
            set
            {
                this.eventQuizMappingIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int postQuizId
        {
            get
            {
                return this.postQuizIdField;
            }
            set
            {
                this.postQuizIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int preQuizId
        {
            get
            {
                return this.preQuizIdField;
            }
            set
            {
                this.preQuizIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyQuizEventMappingDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class CompanyQuizEventMappingDTO : CompanyEventsServiceNamespace.CompanyQuizEventMappingSaveDTO
    {
        
        private CompanyEventsServiceNamespace.CompanyEventDTO acEventInfoField;
        
        private CompanyEventsServiceNamespace.ACDomainDTO companyAcDomainField;
        
        private System.Guid guidField;
        
        private string registrationUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompanyEventsServiceNamespace.CompanyEventDTO acEventInfo
        {
            get
            {
                return this.acEventInfoField;
            }
            set
            {
                this.acEventInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompanyEventsServiceNamespace.ACDomainDTO companyAcDomain
        {
            get
            {
                return this.companyAcDomainField;
            }
            set
            {
                this.companyAcDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registrationUrl
        {
            get
            {
                return this.registrationUrlField;
            }
            set
            {
                this.registrationUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyEventDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class CompanyEventDTO : object
    {
        
        private int companyIdField;
        
        private System.DateTime dateBeginField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateEndField;
        
        private System.DateTime dateModifiedField;
        
        private string descField;
        
        private bool isMappedToQuizzesField;
        
        private bool isSeminarField;
        
        private string meetingUrlField;
        
        private string nameField;
        
        private string scoIdField;
        
        private string urlPathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateBegin
        {
            get
            {
                return this.dateBeginField;
            }
            set
            {
                this.dateBeginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateEnd
        {
            get
            {
                return this.dateEndField;
            }
            set
            {
                this.dateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isMappedToQuizzes
        {
            get
            {
                return this.isMappedToQuizzesField;
            }
            set
            {
                this.isMappedToQuizzesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSeminar
        {
            get
            {
                return this.isSeminarField;
            }
            set
            {
                this.isSeminarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string meetingUrl
        {
            get
            {
                return this.meetingUrlField;
            }
            set
            {
                this.meetingUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scoId
        {
            get
            {
                return this.scoIdField;
            }
            set
            {
                this.scoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urlPath
        {
            get
            {
                return this.urlPathField;
            }
            set
            {
                this.urlPathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ACDomainDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class ACDomainDTO : object
    {
        
        private int companyIdField;
        
        private int domainIdField;
        
        private bool isDefaultField;
        
        private string passwordField;
        
        private string pathField;
        
        private string userField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int domainId
        {
            get
            {
                return this.domainIdField;
            }
            set
            {
                this.domainIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
    public partial class Error : object
    {
        
        private int errorCodeField;
        
        private string errorDetailField;
        
        private string errorMessageField;
        
        private string errorTypeField;
        
        private string[] faultEntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorDetail
        {
            get
            {
                return this.errorDetailField;
            }
            set
            {
                this.errorDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] faultEntities
        {
            get
            {
                return this.faultEntitiesField;
            }
            set
            {
                this.faultEntitiesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyEventsServiceNamespace.ICompanyEventsService")]
    public interface ICompanyEventsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetById", ReplyAction="http://tempuri.org/ICompanyEventsService/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO> GetByIdAsync(int eventQuizMappingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompany", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAsync(int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServer", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServerErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAcServerAsync(int companyAcServerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServerWithPastEvents" +
            "", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServerWithPastEvents" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventsByCompanyAcServerWithPastEvents" +
            "ErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAcServerWithPastEventsAsync(int companyAcServerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappings", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByCompanyId", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByCompanyIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByCompanyIdErrorFaul" +
            "t", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsByCompanyIdAsync(int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByAcServerId", ReplyAction="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByAcServerIdResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetEventQuizMappingsByAcServerIdErrorFau" +
            "lt", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsByAcServerIdAsync(int acServerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/DeleteById", ReplyAction="http://tempuri.org/ICompanyEventsService/DeleteByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/DeleteByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<int> DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/GetByGuid", ReplyAction="http://tempuri.org/ICompanyEventsService/GetByGuidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/GetByGuidErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO> GetByGuidAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyEventsService/Save", ReplyAction="http://tempuri.org/ICompanyEventsService/SaveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CompanyEventsServiceNamespace.Error), Action="http://tempuri.org/ICompanyEventsService/SaveErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingSaveDTO> SaveAsync(CompanyEventsServiceNamespace.CompanyQuizEventMappingSaveDTO eventQuizMapping);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface ICompanyEventsServiceChannel : CompanyEventsServiceNamespace.ICompanyEventsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CompanyEventsServiceClient : System.ServiceModel.ClientBase<CompanyEventsServiceNamespace.ICompanyEventsService>, CompanyEventsServiceNamespace.ICompanyEventsService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompanyEventsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CompanyEventsServiceClient.GetBindingForEndpoint(endpointConfiguration), CompanyEventsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyEventsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompanyEventsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyEventsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompanyEventsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyEventsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO> GetByIdAsync(int eventQuizMappingId)
        {
            return base.Channel.GetByIdAsync(eventQuizMappingId);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAsync(int companyId)
        {
            return base.Channel.GetEventsByCompanyAsync(companyId);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAcServerAsync(int companyAcServerId)
        {
            return base.Channel.GetEventsByCompanyAcServerAsync(companyAcServerId);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyEventDTO[]> GetEventsByCompanyAcServerWithPastEventsAsync(int companyAcServerId)
        {
            return base.Channel.GetEventsByCompanyAcServerWithPastEventsAsync(companyAcServerId);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsAsync()
        {
            return base.Channel.GetEventQuizMappingsAsync();
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsByCompanyIdAsync(int companyId)
        {
            return base.Channel.GetEventQuizMappingsByCompanyIdAsync(companyId);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO[]> GetEventQuizMappingsByAcServerIdAsync(int acServerId)
        {
            return base.Channel.GetEventQuizMappingsByAcServerIdAsync(acServerId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteByIdAsync(int id)
        {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingDTO> GetByGuidAsync(System.Guid id)
        {
            return base.Channel.GetByGuidAsync(id);
        }
        
        public System.Threading.Tasks.Task<CompanyEventsServiceNamespace.CompanyQuizEventMappingSaveDTO> SaveAsync(CompanyEventsServiceNamespace.CompanyQuizEventMappingSaveDTO eventQuizMapping)
        {
            return base.Channel.SaveAsync(eventQuizMapping);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompanyEventsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_ICompanyEventsService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompanyEventsService))
            {
                return new System.ServiceModel.EndpointAddress("http://app.edugamecloud.com/services/CompanyEventsService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_ICompanyEventsService))
            {
                return new System.ServiceModel.EndpointAddress("http://app.edugamecloud.com/services/CompanyEventsService.svc/amf");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICompanyEventsService,
            
            CustomBinding_ICompanyEventsService,
        }
    }
}
