//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Emails", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Your account has been removed from the system.
        /// </summary>
        internal static string AccountDeletedSubject {
            get {
                return ResourceManager.GetString("AccountDeletedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Your login credentials have been changed.
        /// </summary>
        internal static string ChangePasswordSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Contact Form: {0}.
        /// </summary>
        internal static string ContactAdminSubject {
            get {
                return ResourceManager.GetString("ContactAdminSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Request..
        /// </summary>
        internal static string ContactUsSubject {
            get {
                return ResourceManager.GetString("ContactUsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Your your installation has been canceled.
        /// </summary>
        internal static string InstallationCanceledSubject {
            get {
                return ResourceManager.GetString("InstallationCanceledSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your purchase!.
        /// </summary>
        internal static string ReceiptSubject {
            get {
                return ResourceManager.GetString("ReceiptSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trial was requested.
        /// </summary>
        internal static string RequestTrialSubject {
            get {
                return ResourceManager.GetString("RequestTrialSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Token key delivery.
        /// </summary>
        internal static string TokenDeliverySubject {
            get {
                return ResourceManager.GetString("TokenDeliverySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial request for {0}.
        /// </summary>
        internal static string TrialRequest {
            get {
                return ResourceManager.GetString("TrialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Team {0}!.
        /// </summary>
        internal static string UserCreatedSubject {
            get {
                return ResourceManager.GetString("UserCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Your account has been removed from the system.
        /// </summary>
        internal static string UserDeletedSubject {
            get {
                return ResourceManager.GetString("UserDeletedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Your login name has been changed.
        /// </summary>
        internal static string UserEmailEditedSubject {
            get {
                return ResourceManager.GetString("UserEmailEditedSubject", resourceCulture);
            }
        }
    }
}
