//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from the T4 template.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using FluentNHibernate.Mapping;
using Esynctraining.Persistence.Mappings;
using EdugameCloud.Lti.Domain.Entities;

namespace EdugameCloud.Lti.Persistence.Mappings
{
    public sealed partial class AcCachePrincipalMap : BaseClassMap<AcCachePrincipal>
    {
        public AcCachePrincipalMap()
        {
            Table("[AcCachePrincipal]");
            Map(x => x.LmsCompanyId).Not.Nullable();
            Map(x => x.AccountId).Nullable();
            Map(x => x.DisplayId).Nullable();
            Map(x => x.Email).Nullable();
            Map(x => x.FirstName).Nullable();
            Map(x => x.HasChildren).Nullable();
            Map(x => x.IsHidden).Nullable();
            Map(x => x.IsPrimary).Nullable();
            Map(x => x.LastName).Nullable();
            Map(x => x.Login).Nullable();
            Map(x => x.Name).Nullable();
            Map(x => x.PrincipalId).Nullable();
            Map(x => x.Type).Nullable();

            ExtraMapping();
        }

        partial void ExtraMapping();

    }

}
