//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServiceNamespace
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDTO", Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class FileDTO : object
    {
        
        private System.Nullable<int> createdByField;
        
        private double dateCreatedField;
        
        private System.Guid fileIdField;
        
        private string fileNameField;
        
        private System.Nullable<int> heightField;
        
        private System.Nullable<int> widthField;
        
        private System.Nullable<int> xField;
        
        private System.Nullable<int> yField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> createdBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid fileId
        {
            get
            {
                return this.fileIdField;
            }
            set
            {
                this.fileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
    public partial class Error : object
    {
        
        private int errorCodeField;
        
        private string errorDetailField;
        
        private string errorMessageField;
        
        private string errorTypeField;
        
        private string[] faultEntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorDetail
        {
            get
            {
                return this.errorDetailField;
            }
            set
            {
                this.errorDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] faultEntities
        {
            get
            {
                return this.faultEntitiesField;
            }
            set
            {
                this.faultEntitiesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceNamespace.IFileService")]
    public interface IFileService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/FileUploadEnd", ReplyAction="http://tempuri.org/IFileService/FileUploadEndResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FileServiceNamespace.Error), Action="http://tempuri.org/IFileService/FileUploadEndErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> FileUploadEndAsync(string webOrbId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetById", ReplyAction="http://tempuri.org/IFileService/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FileServiceNamespace.Error), Action="http://tempuri.org/IFileService/GetByIdErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> GetByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/FileUploadFailed", ReplyAction="http://tempuri.org/IFileService/FileUploadFailedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FileServiceNamespace.Error), Action="http://tempuri.org/IFileService/FileUploadFailedErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task FileUploadFailedAsync(string webOrbId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/InitializeFileUpload", ReplyAction="http://tempuri.org/IFileService/InitializeFileUploadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FileServiceNamespace.Error), Action="http://tempuri.org/IFileService/InitializeFileUploadErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<string> InitializeFileUploadAsync(FileServiceNamespace.FileDTO file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Save", ReplyAction="http://tempuri.org/IFileService/SaveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FileServiceNamespace.Error), Action="http://tempuri.org/IFileService/SaveErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/Esynctraining.Core.Domain.Entities")]
        System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> SaveAsync(FileServiceNamespace.FileDTO file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IFileServiceChannel : FileServiceNamespace.IFileService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<FileServiceNamespace.IFileService>, FileServiceNamespace.IFileService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), FileServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> FileUploadEndAsync(string webOrbId)
        {
            return base.Channel.FileUploadEndAsync(webOrbId);
        }
        
        public System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> GetByIdAsync(System.Guid id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task FileUploadFailedAsync(string webOrbId)
        {
            return base.Channel.FileUploadFailedAsync(webOrbId);
        }
        
        public System.Threading.Tasks.Task<string> InitializeFileUploadAsync(FileServiceNamespace.FileDTO file)
        {
            return base.Channel.InitializeFileUploadAsync(file);
        }
        
        public System.Threading.Tasks.Task<FileServiceNamespace.FileDTO> SaveAsync(FileServiceNamespace.FileDTO file)
        {
            return base.Channel.SaveAsync(file);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IFileService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileService))
            {
                return new System.ServiceModel.EndpointAddress("http://app.edugamecloud.com/services/FileService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IFileService))
            {
                return new System.ServiceModel.EndpointAddress("http://app.edugamecloud.com/services/FileService.svc/amf");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFileService,
            
            CustomBinding_IFileService,
        }
    }
}
