//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdugameCloud.Lti.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdugameCloud.Lti.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get Adobe Connect BreezeSession.
        /// </summary>
        public static string CanNotGetBreezeSession {
            get {
                return ResourceManager.GetString("CanNotGetBreezeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save user information in database. Please contact system administrator..
        /// </summary>
        public static string CanSaveToDb {
            get {
                return ResourceManager.GetString("CanSaveToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. .
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is occured. Try again later or contact your administrator..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is occured. .
        /// </summary>
        public static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you provided is incorrect. Please try again..
        /// </summary>
        public static string IncorrectAcPassword {
            get {
                return ResourceManager.GetString("IncorrectAcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review LTI integration. Possible you have invalid External Tool URL..
        /// </summary>
        public static string LtiExternalToolUrl {
            get {
                return ResourceManager.GetString("LtiExternalToolUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LTI request.
        /// </summary>
        public static string LtiInvalidRequest {
            get {
                return ResourceManager.GetString("LtiInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Adobe Connect account does not exist for you. Please contact administrator..
        /// </summary>
        public static string LtiNoAcAccount {
            get {
                return ResourceManager.GetString("LtiNoAcAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, LMS Admin is not set for current license. Please contact administrator..
        /// </summary>
        public static string LtiNoLmsAdmin {
            get {
                return ResourceManager.GetString("LtiNoLmsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LTI integration is already set for different domain..
        /// </summary>
        public static string LtiValidationDifferentDomain {
            get {
                return ResourceManager.GetString("LtiValidationDifferentDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your company doesn&apos;t have any active license. Please contact administrator..
        /// </summary>
        public static string LtiValidationInactiveCompanyLicense {
            get {
                return ResourceManager.GetString("LtiValidationInactiveCompanyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMS License is not active. Please contact administrator..
        /// </summary>
        public static string LtiValidationInactiveLmsLicense {
            get {
                return ResourceManager.GetString("LtiValidationInactiveLmsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Adobe Connect integration is not set up..
        /// </summary>
        public static string LtiValidationNoSetup {
            get {
                return ResourceManager.GetString("LtiValidationNoSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find LMS information. Please, contact system administrator..
        /// </summary>
        public static string NoLmsInformation {
            get {
                return ResourceManager.GetString("NoLmsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find session information for current user. Please, enable cookies or try to open LTI application in a different browser..
        /// </summary>
        public static string NoSessionInformation {
            get {
                return ResourceManager.GetString("NoSessionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user with principal id {0} found in Adobe Connect..
        /// </summary>
        public static string NoUserByPrincipalIdFound {
            get {
                return ResourceManager.GetString("NoUserByPrincipalIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user with id {0} found..
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; already exists in Adobe Connect..
        /// </summary>
        public static string PrincipalValidateAlreadyInAc {
            get {
                return ResourceManager.GetString("PrincipalValidateAlreadyInAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must be between 1 and 60 characters long..
        /// </summary>
        public static string PrincipalValidateEmailLength {
            get {
                return ResourceManager.GetString("PrincipalValidateEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must be between 1 and 60 characters long..
        /// </summary>
        public static string PrincipalValidateLoginLength {
            get {
                return ResourceManager.GetString("PrincipalValidateLoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combined length of First and Last name must be between 1 and 60 characters..
        /// </summary>
        public static string PrincipalValidateNameLength {
            get {
                return ResourceManager.GetString("PrincipalValidateNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timed out. Please refresh the page..
        /// </summary>
        public static string SessionTimeOut {
            get {
                return ResourceManager.GetString("SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Adobe Connect user is already a participant of the meeting..
        /// </summary>
        public static string UserIsAlreadyParticipant {
            get {
                return ResourceManager.GetString("UserIsAlreadyParticipant", resourceCulture);
            }
        }
    }
}
