using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EdugameCloud.Lti.Core.Constants;
using EdugameCloud.Lti.Domain.Entities;
using EdugameCloud.Lti.DTO;
using Esynctraining.Core.Domain;

namespace EdugameCloud.Lti.Controllers
{
    public partial class LtiController
    {
        [HttpPost]
        public virtual ActionResult UpdateUser(string lmsProviderName, LmsUserDTO[] users, int meetingId)
        {
            LmsCompany credentials = null;
            if (string.IsNullOrWhiteSpace(lmsProviderName))
                throw new ArgumentException("lmsProviderName can't be empty", nameof(lmsProviderName));
            if (meetingId <= 0)
                throw new ArgumentOutOfRangeException(nameof(meetingId));

            var session = GetReadOnlySession(lmsProviderName);
            credentials = session.LmsCompany;
            string lastError = null;
            var updatedUsers = new List<LmsUserDTO>();
            foreach (var user in users)
            {
                try
                {
                    // TRICK: client-side passes 'email' but user.GetEmail() expects primary-email
                    if (string.IsNullOrEmpty(user.primary_email) && !string.IsNullOrEmpty(user.email))
                        user.primary_email = user.email;

                    LmsUserDTO updatedUser = null;
                    string error;
                    if (user.guest_id.HasValue)
                    {
                        updatedUser = this.usersSetup.UpdateGuest(
                            credentials,
                            this.GetAdobeConnectProvider(credentials),
                            session.LtiSession.LtiParam,
                            user,
                            meetingId,
                            out error);
                    }
                    else
                    {
                        updatedUser = this.usersSetup.UpdateUser(
                            credentials,
                            this.GetAdobeConnectProvider(credentials),
                            session.LtiSession.LtiParam,
                            user,
                            meetingId,
                            out error);
                    }

                    if (!string.IsNullOrEmpty(error))
                    {
                        logger.Error($"[UpdateUsers] {error}. UserId={user.id}, MeetingId={meetingId}");
                        lastError = error;
                    }
                    else
                    {
                        // TRICK: if user not found in LMS - return original record from client  (remove user from meeting participant list - user doesn't exist in LMS)
                        updatedUsers.Add(updatedUser ?? user);
                    }
                }
                catch (Exception ex)
                {
                    lastError = GetOutputErrorMessage("UpdateUsers", credentials, ex);
                    logger.Error($"[RemoveUsers] UserId={user.id}, MeetingId={meetingId}, {lastError}", ex);
                }
            }

            if (string.IsNullOrEmpty(lastError))
                return Json(OperationResultWithData<IEnumerable<LmsUserDTO>>.Success(updatedUsers));

            return Json(new OperationResultWithData<IEnumerable<LmsUserDTO>>
            {
                Message = Resources.Messages.UsersCouldNotBeUpdated,
                Data = updatedUsers
            });
        }

        // NOTE: id - is userID (Id of the user in LMS) or value like "MeetingSetup.model.User-47" (generated by extJS if id was empty - if user doesn't exists in LMS)
        [HttpPost]
        public virtual ActionResult RemoveFromAcMeeting(string lmsProviderName, int meetingId, LmsUserDTO[] users)
        {
            LmsCompany credentials = null;
            if (string.IsNullOrWhiteSpace(lmsProviderName))
                throw new ArgumentException("lmsProviderName can't be empty", nameof(lmsProviderName));
            if (meetingId <= 0)
                throw new ArgumentOutOfRangeException(nameof(meetingId));

            var session = GetReadOnlySession(lmsProviderName);
            credentials = session.LmsCompany;

            if (!credentials.GetSetting<bool>(LmsCompanySettingNames.EnableRemoveUser, true))
                return Json(OperationResult.Error("Operation is not enabled."));

            string error;
            string lastError = null;
            List<LmsUserDTO> removedUsers = new List<LmsUserDTO>();
            foreach (var user in users)
            {
                try
                {
                    if (user.guest_id.HasValue)
                    {
                        this.usersSetup.DeleteGuestFromAcMeeting(
                            credentials,
                            this.GetAdobeConnectProvider(credentials),
                            session.LtiSession.LtiParam,
                            user.ac_id,
                            meetingId,
                            user.guest_id.Value,
                            out error);
                    }
                    else
                    {
                        this.usersSetup.DeleteUserFromAcMeeting(
                            credentials,
                            this.GetAdobeConnectProvider(credentials),
                            session.LtiSession.LtiParam,
                            user.ac_id,
                            meetingId,
                            out error);
                    }
                    if (!string.IsNullOrEmpty(error))
                    {
                        logger.Error($"[RemoveUsers] {error}. UserId={user.id}, MeetingId={meetingId}");
                        lastError = error;
                    }
                    else
                    {
                        removedUsers.Add(user);
                    }
                }
                catch (Exception ex)
                {
                    lastError = GetOutputErrorMessage("RemoveUsers", credentials, ex);
                    logger.Error($"[RemoveUsers] UserId={user.id}, MeetingId={meetingId}, {lastError}", ex);
                }
            }

            if (string.IsNullOrEmpty(lastError))
                return Json(OperationResultWithData<IEnumerable<LmsUserDTO>>.Success(removedUsers));

            return Json(new OperationResultWithData<IEnumerable<LmsUserDTO>>
            {
                Message = Resources.Messages.UsersCouldNotBeRemoved,
                Data = removedUsers
            });
        }
    }
}