// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using EdugameCloud.MVC;
namespace EdugameCloud.MVC.Controllers
{
    public partial class LtiController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LtiController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AuthenticationCallback()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AuthenticationCallback);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult SaveSettings()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.SaveSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult CheckPasswordBeforeJoin()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.CheckPasswordBeforeJoin);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetSettings()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult DeleteRecording()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.DeleteRecording);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetHtmlPage()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetHtmlPage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetMeeting()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetMeeting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetRecordings()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetRecordings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetTemplates()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetTemplates);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetUsers()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetUsers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetAttendanceReport()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetAttendanceReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetSessionsReport()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.GetSessionsReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult JoinMeeting()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.JoinMeeting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult JoinRecording()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.JoinRecording);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditRecording()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditRecording);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetRecordingFlv()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetRecordingFlv);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LoginWithProvider()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LoginWithProvider);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RedirectToErrorPage()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RedirectToErrorPage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult UpdateMeeting()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.UpdateMeeting);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult UpdateUser()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.UpdateUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult SetDefaultRolesForNonParticipants()
        {
            return new T4MVC_JsonResult(Area, Name, ActionNames.SetDefaultRolesForNonParticipants);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LtiController Actions { get { return EdugameCloudT4.Lti; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Lti";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Lti";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AuthenticationCallback = "callback";
            public readonly string SaveSettings = "SaveSettings";
            public readonly string CheckPasswordBeforeJoin = "CheckPasswordBeforeJoin";
            public readonly string GetSettings = "GetSettings";
            public readonly string DeleteRecording = "DeleteRecording";
            public readonly string GetHtmlPage = "GetHtmlPage";
            public readonly string GetMeeting = "GetMeeting";
            public readonly string GetRecordings = "GetRecordings";
            public readonly string GetTemplates = "GetTemplates";
            public readonly string GetUsers = "GetUsers";
            public readonly string GetAttendanceReport = "GetAttendanceReport";
            public readonly string GetSessionsReport = "GetSessionsReport";
            public readonly string Index = "Index";
            public readonly string JoinMeeting = "JoinMeeting";
            public readonly string JoinRecording = "JoinRecording";
            public readonly string EditRecording = "EditRecording";
            public readonly string GetRecordingFlv = "GetRecordingFlv";
            public readonly string LoginWithProvider = "login";
            public readonly string RedirectToErrorPage = "RedirectToErrorPage";
            public readonly string UpdateMeeting = "UpdateMeeting";
            public readonly string UpdateUser = "UpdateUser";
            public readonly string SetDefaultRolesForNonParticipants = "SetDefaultRolesForNonParticipants";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AuthenticationCallback = "callback";
            public const string SaveSettings = "SaveSettings";
            public const string CheckPasswordBeforeJoin = "CheckPasswordBeforeJoin";
            public const string GetSettings = "GetSettings";
            public const string DeleteRecording = "DeleteRecording";
            public const string GetHtmlPage = "GetHtmlPage";
            public const string GetMeeting = "GetMeeting";
            public const string GetRecordings = "GetRecordings";
            public const string GetTemplates = "GetTemplates";
            public const string GetUsers = "GetUsers";
            public const string GetAttendanceReport = "GetAttendanceReport";
            public const string GetSessionsReport = "GetSessionsReport";
            public const string Index = "Index";
            public const string JoinMeeting = "JoinMeeting";
            public const string JoinRecording = "JoinRecording";
            public const string EditRecording = "EditRecording";
            public const string GetRecordingFlv = "GetRecordingFlv";
            public const string LoginWithProvider = "login";
            public const string RedirectToErrorPage = "RedirectToErrorPage";
            public const string UpdateMeeting = "UpdateMeeting";
            public const string UpdateUser = "UpdateUser";
            public const string SetDefaultRolesForNonParticipants = "SetDefaultRolesForNonParticipants";
        }


        static readonly ActionParamsClass_AuthenticationCallback s_params_AuthenticationCallback = new ActionParamsClass_AuthenticationCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AuthenticationCallback AuthenticationCallbackParams { get { return s_params_AuthenticationCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AuthenticationCallback
        {
            public readonly string __provider__ = "__provider__";
            public readonly string __sid__ = "__sid__";
            public readonly string code = "code";
            public readonly string state = "state";
            public readonly string providerKey = "providerKey";
        }
        static readonly ActionParamsClass_SaveSettings s_params_SaveSettings = new ActionParamsClass_SaveSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSettings SaveSettingsParams { get { return s_params_SaveSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSettings
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_CheckPasswordBeforeJoin s_params_CheckPasswordBeforeJoin = new ActionParamsClass_CheckPasswordBeforeJoin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckPasswordBeforeJoin CheckPasswordBeforeJoinParams { get { return s_params_CheckPasswordBeforeJoin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckPasswordBeforeJoin
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_GetSettings s_params_GetSettings = new ActionParamsClass_GetSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSettings GetSettingsParams { get { return s_params_GetSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSettings
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_DeleteRecording s_params_DeleteRecording = new ActionParamsClass_DeleteRecording();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteRecording DeleteRecordingParams { get { return s_params_DeleteRecording; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteRecording
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetHtmlPage s_params_GetHtmlPage = new ActionParamsClass_GetHtmlPage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetHtmlPage GetHtmlPageParams { get { return s_params_GetHtmlPage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetHtmlPage
        {
            public readonly string path = "path";
        }
        static readonly ActionParamsClass_GetMeeting s_params_GetMeeting = new ActionParamsClass_GetMeeting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMeeting GetMeetingParams { get { return s_params_GetMeeting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMeeting
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_GetRecordings s_params_GetRecordings = new ActionParamsClass_GetRecordings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetRecordings GetRecordingsParams { get { return s_params_GetRecordings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetRecordings
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_GetTemplates s_params_GetTemplates = new ActionParamsClass_GetTemplates();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetTemplates GetTemplatesParams { get { return s_params_GetTemplates; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetTemplates
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_GetUsers s_params_GetUsers = new ActionParamsClass_GetUsers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetUsers GetUsersParams { get { return s_params_GetUsers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetUsers
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_GetAttendanceReport s_params_GetAttendanceReport = new ActionParamsClass_GetAttendanceReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAttendanceReport GetAttendanceReportParams { get { return s_params_GetAttendanceReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAttendanceReport
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string startIndex = "startIndex";
            public readonly string limit = "limit";
        }
        static readonly ActionParamsClass_GetSessionsReport s_params_GetSessionsReport = new ActionParamsClass_GetSessionsReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSessionsReport GetSessionsReportParams { get { return s_params_GetSessionsReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSessionsReport
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string startIndex = "startIndex";
            public readonly string limit = "limit";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_JoinMeeting s_params_JoinMeeting = new ActionParamsClass_JoinMeeting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_JoinMeeting JoinMeetingParams { get { return s_params_JoinMeeting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_JoinMeeting
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ActionParamsClass_JoinRecording s_params_JoinRecording = new ActionParamsClass_JoinRecording();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_JoinRecording JoinRecordingParams { get { return s_params_JoinRecording; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_JoinRecording
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string recordingUrl = "recordingUrl";
        }
        static readonly ActionParamsClass_EditRecording s_params_EditRecording = new ActionParamsClass_EditRecording();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditRecording EditRecordingParams { get { return s_params_EditRecording; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditRecording
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string recordingUrl = "recordingUrl";
        }
        static readonly ActionParamsClass_GetRecordingFlv s_params_GetRecordingFlv = new ActionParamsClass_GetRecordingFlv();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetRecordingFlv GetRecordingFlvParams { get { return s_params_GetRecordingFlv; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetRecordingFlv
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string recordingUrl = "recordingUrl";
        }
        static readonly ActionParamsClass_LoginWithProvider s_params_LoginWithProvider = new ActionParamsClass_LoginWithProvider();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoginWithProvider LoginWithProviderParams { get { return s_params_LoginWithProvider; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoginWithProvider
        {
            public readonly string provider = "provider";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RedirectToErrorPage s_params_RedirectToErrorPage = new ActionParamsClass_RedirectToErrorPage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectToErrorPage RedirectToErrorPageParams { get { return s_params_RedirectToErrorPage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectToErrorPage
        {
            public readonly string errorText = "errorText";
        }
        static readonly ActionParamsClass_UpdateMeeting s_params_UpdateMeeting = new ActionParamsClass_UpdateMeeting();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateMeeting UpdateMeetingParams { get { return s_params_UpdateMeeting; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateMeeting
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string meeting = "meeting";
        }
        static readonly ActionParamsClass_UpdateUser s_params_UpdateUser = new ActionParamsClass_UpdateUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateUser UpdateUserParams { get { return s_params_UpdateUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateUser
        {
            public readonly string lmsProviderName = "lmsProviderName";
            public readonly string user = "user";
        }
        static readonly ActionParamsClass_SetDefaultRolesForNonParticipants s_params_SetDefaultRolesForNonParticipants = new ActionParamsClass_SetDefaultRolesForNonParticipants();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetDefaultRolesForNonParticipants SetDefaultRolesForNonParticipantsParams { get { return s_params_SetDefaultRolesForNonParticipants; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetDefaultRolesForNonParticipants
        {
            public readonly string lmsProviderName = "lmsProviderName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Error = "Error";
                public readonly string Redirect = "Redirect";
            }
            public readonly string Error = "~/Views/Lti/Error.cshtml";
            public readonly string Redirect = "~/Views/Lti/Redirect.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_LtiController : EdugameCloud.MVC.Controllers.LtiController
    {
        public T4MVC_LtiController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AuthenticationCallback(string __provider__, string __sid__, string code, string state, string providerKey)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AuthenticationCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "__provider__", __provider__);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "__sid__", __sid__);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "state", state);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "providerKey", providerKey);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult SaveSettings(EdugameCloud.Lti.DTO.LmsUserSettingsDTO settings)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.SaveSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult CheckPasswordBeforeJoin(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.CheckPasswordBeforeJoin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetSettings(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult DeleteRecording(string lmsProviderName, string id)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.DeleteRecording);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetHtmlPage(string path)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetHtmlPage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "path", path);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetMeeting(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetMeeting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetRecordings(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetRecordings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetTemplates(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetTemplates);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetUsers(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetUsers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetAttendanceReport(string lmsProviderName, int startIndex, int limit)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetAttendanceReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "startIndex", startIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "limit", limit);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetSessionsReport(string lmsProviderName, int startIndex, int limit)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetSessionsReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "startIndex", startIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "limit", limit);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(EdugameCloud.Lti.DTO.LtiParamDTO model)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult JoinMeeting(string lmsProviderName)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.JoinMeeting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult JoinRecording(string lmsProviderName, string recordingUrl)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.JoinRecording);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "recordingUrl", recordingUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditRecording(string lmsProviderName, string recordingUrl)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditRecording);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "recordingUrl", recordingUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetRecordingFlv(string lmsProviderName, string recordingUrl)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetRecordingFlv);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "recordingUrl", recordingUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoginWithProvider(string provider, EdugameCloud.Lti.DTO.LtiParamDTO model)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LoginWithProvider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RedirectToErrorPage(string errorText)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RedirectToErrorPage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "errorText", errorText);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult UpdateMeeting(string lmsProviderName, EdugameCloud.Lti.DTO.MeetingDTO meeting)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.UpdateMeeting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "meeting", meeting);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult UpdateUser(string lmsProviderName, EdugameCloud.Lti.DTO.LmsUserDTO user)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.UpdateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "user", user);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult SetDefaultRolesForNonParticipants(string lmsProviderName)
        {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.SetDefaultRolesForNonParticipants);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lmsProviderName", lmsProviderName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
