// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using EdugameCloud.MVC;
namespace EdugameCloud.MVC.Controllers
{
    public partial class SocialController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SocialController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RealtimeCallback()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RealtimeCallback);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AuthenticationCallback()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AuthenticationCallback);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SocialController Actions { get { return EdugameCloudT4.Social; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Social";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Social";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string RealtimeCallback = "realtime-callback";
            public readonly string AuthenticationCallback = "callback";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string RealtimeCallback = "realtime-callback";
            public const string AuthenticationCallback = "callback";
        }


        static readonly ActionParamsClass_RealtimeCallback s_params_RealtimeCallback = new ActionParamsClass_RealtimeCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RealtimeCallback RealtimeCallbackParams { get { return s_params_RealtimeCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RealtimeCallback
        {
            public readonly string provider = "provider";
            public readonly string hub = "hub";
        }
        static readonly ActionParamsClass_AuthenticationCallback s_params_AuthenticationCallback = new ActionParamsClass_AuthenticationCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AuthenticationCallback AuthenticationCallbackParams { get { return s_params_AuthenticationCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AuthenticationCallback
        {
            public readonly string provider = "provider";
            public readonly string key = "key";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string LoggedIn = "LoggedIn";
            }
            public readonly string LoggedIn = "~/Views/Social/LoggedIn.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SocialController : EdugameCloud.MVC.Controllers.SocialController
    {
        public T4MVC_SocialController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult RealtimeCallback(string provider, EdugameCloud.MVC.Social.Subscriptions.InstagramSubscriptionHub hub)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RealtimeCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hub", hub);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RealtimeCallback(string provider)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RealtimeCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AuthenticationCallback(string provider, string key)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AuthenticationCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "key", key);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
