//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EdugameCloud.ACEvents.Web.QuizResultServiceNamespace {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IQuizResultService", Namespace="http://tempuri.org/")]
    public partial class QuizResultService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAllOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QuizResultService() {
            this.Url = global::EdugameCloud.ACEvents.Web.Properties.Settings.Default.EdugameCloud_ACEvents_Web_QuizResultServiceNamespace_QuizResultService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        public event DeleteByIdCompletedEventHandler DeleteByIdCompleted;
        
        /// <remarks/>
        public event GetByIdCompletedEventHandler GetByIdCompleted;
        
        /// <remarks/>
        public event GetByGuidCompletedEventHandler GetByGuidCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event SaveAllCompletedEventHandler SaveAllCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
        public QuizResultDTO[] GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((QuizResultDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAsync(object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[0], this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/DeleteById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteById(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out int DeleteByIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteByIdResultSpecified) {
            object[] results = this.Invoke("DeleteById", new object[] {
                        id,
                        idSpecified});
            DeleteByIdResult = ((int)(results[0]));
            DeleteByIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteByIdAsync(int id, bool idSpecified) {
            this.DeleteByIdAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteByIdAsync(int id, bool idSpecified, object userState) {
            if ((this.DeleteByIdOperationCompleted == null)) {
                this.DeleteByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteByIdOperationCompleted);
            }
            this.InvokeAsync("DeleteById", new object[] {
                        id,
                        idSpecified}, this.DeleteByIdOperationCompleted, userState);
        }
        
        private void OnDeleteByIdOperationCompleted(object arg) {
            if ((this.DeleteByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteByIdCompleted(this, new DeleteByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/GetById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QuizResultDTO GetById(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("GetById", new object[] {
                        id,
                        idSpecified});
            return ((QuizResultDTO)(results[0]));
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id, bool idSpecified) {
            this.GetByIdAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id, bool idSpecified, object userState) {
            if ((this.GetByIdOperationCompleted == null)) {
                this.GetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIdOperationCompleted);
            }
            this.InvokeAsync("GetById", new object[] {
                        id,
                        idSpecified}, this.GetByIdOperationCompleted, userState);
        }
        
        private void OnGetByIdOperationCompleted(object arg) {
            if ((this.GetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/GetByGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QuizResultDTO GetByGuid(string guid) {
            object[] results = this.Invoke("GetByGuid", new object[] {
                        guid});
            return ((QuizResultDTO)(results[0]));
        }
        
        /// <remarks/>
        public void GetByGuidAsync(string guid) {
            this.GetByGuidAsync(guid, null);
        }
        
        /// <remarks/>
        public void GetByGuidAsync(string guid, object userState) {
            if ((this.GetByGuidOperationCompleted == null)) {
                this.GetByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByGuidOperationCompleted);
            }
            this.InvokeAsync("GetByGuid", new object[] {
                        guid}, this.GetByGuidOperationCompleted, userState);
        }
        
        private void OnGetByGuidOperationCompleted(object arg) {
            if ((this.GetByGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByGuidCompleted(this, new GetByGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QuizResultDTO Save([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] QuizResultDTO result) {
            object[] results = this.Invoke("Save", new object[] {
                        result});
            return ((QuizResultDTO)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(QuizResultDTO result) {
            this.SaveAsync(result, null);
        }
        
        /// <remarks/>
        public void SaveAsync(QuizResultDTO result, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        result}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQuizResultService/SaveAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QuizResultSaveAllDTO SaveAll([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")] QuizResultDTO[] results) {
            object[] results1 = this.Invoke("SaveAll", new object[] {
                        results});
            return ((QuizResultSaveAllDTO)(results1[0]));
        }
        
        /// <remarks/>
        public void SaveAllAsync(QuizResultDTO[] results) {
            this.SaveAllAsync(results, null);
        }
        
        /// <remarks/>
        public void SaveAllAsync(QuizResultDTO[] results, object userState) {
            if ((this.SaveAllOperationCompleted == null)) {
                this.SaveAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAllOperationCompleted);
            }
            this.InvokeAsync("SaveAll", new object[] {
                        results}, this.SaveAllOperationCompleted, userState);
        }
        
        private void OnSaveAllOperationCompleted(object arg) {
            if ((this.SaveAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAllCompleted(this, new SaveAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class QuizResultDTO {
        
        private string acEmailField;
        
        private int acSessionIdField;
        
        private int appInFocusTimeField;
        
        private bool appInFocusTimeFieldSpecified;
        
        private int appMaximizedTimeField;
        
        private bool appMaximizedTimeFieldSpecified;
        
        private int companyIdField;
        
        private double dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private string emailField;
        
        private double endTimeField;
        
        private bool endTimeFieldSpecified;
        
        private System.Nullable<int> eventQuizMappingIdField;
        
        private bool eventQuizMappingIdFieldSpecified;
        
        private string guidField;
        
        private bool isArchiveField;
        
        private bool isArchiveFieldSpecified;
        
        private bool isCompletedField;
        
        private bool isCompletedFieldSpecified;
        
        private int lmsIdField;
        
        private bool lmsIdFieldSpecified;
        
        private int lmsUserParametersIdField;
        
        private bool lmsUserParametersIdFieldSpecified;
        
        private string participantNameField;
        
        private int quizIdField;
        
        private int quizResultIdField;
        
        private bool quizResultIdFieldSpecified;
        
        private int scoreField;
        
        private bool scoreFieldSpecified;
        
        private double startTimeField;
        
        private bool startTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string acEmail {
            get {
                return this.acEmailField;
            }
            set {
                this.acEmailField = value;
            }
        }
        
        /// <remarks/>
        public int acSessionId {
            get {
                return this.acSessionIdField;
            }
            set {
                this.acSessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int appInFocusTime {
            get {
                return this.appInFocusTimeField;
            }
            set {
                this.appInFocusTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appInFocusTimeSpecified {
            get {
                return this.appInFocusTimeFieldSpecified;
            }
            set {
                this.appInFocusTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int appMaximizedTime {
            get {
                return this.appMaximizedTimeField;
            }
            set {
                this.appMaximizedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appMaximizedTimeSpecified {
            get {
                return this.appMaximizedTimeFieldSpecified;
            }
            set {
                this.appMaximizedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public double dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreatedSpecified {
            get {
                return this.dateCreatedFieldSpecified;
            }
            set {
                this.dateCreatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public double endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endTimeSpecified {
            get {
                return this.endTimeFieldSpecified;
            }
            set {
                this.endTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> eventQuizMappingId {
            get {
                return this.eventQuizMappingIdField;
            }
            set {
                this.eventQuizMappingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventQuizMappingIdSpecified {
            get {
                return this.eventQuizMappingIdFieldSpecified;
            }
            set {
                this.eventQuizMappingIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public bool isArchive {
            get {
                return this.isArchiveField;
            }
            set {
                this.isArchiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isArchiveSpecified {
            get {
                return this.isArchiveFieldSpecified;
            }
            set {
                this.isArchiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isCompletedSpecified {
            get {
                return this.isCompletedFieldSpecified;
            }
            set {
                this.isCompletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int lmsId {
            get {
                return this.lmsIdField;
            }
            set {
                this.lmsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lmsIdSpecified {
            get {
                return this.lmsIdFieldSpecified;
            }
            set {
                this.lmsIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int lmsUserParametersId {
            get {
                return this.lmsUserParametersIdField;
            }
            set {
                this.lmsUserParametersIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lmsUserParametersIdSpecified {
            get {
                return this.lmsUserParametersIdFieldSpecified;
            }
            set {
                this.lmsUserParametersIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string participantName {
            get {
                return this.participantNameField;
            }
            set {
                this.participantNameField = value;
            }
        }
        
        /// <remarks/>
        public int quizId {
            get {
                return this.quizIdField;
            }
            set {
                this.quizIdField = value;
            }
        }
        
        /// <remarks/>
        public int quizResultId {
            get {
                return this.quizResultIdField;
            }
            set {
                this.quizResultIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quizResultIdSpecified {
            get {
                return this.quizResultIdFieldSpecified;
            }
            set {
                this.quizResultIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EdugameCloud.Core.Domain.DTO")]
    public partial class QuizResultSaveAllDTO {
        
        private string[] faultsField;
        
        private QuizResultDTO[] savedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] faults {
            get {
                return this.faultsField;
            }
            set {
                this.faultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public QuizResultDTO[] saved {
            get {
                return this.savedField;
            }
            set {
                this.savedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuizResultDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuizResultDTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DeleteByIdCompletedEventHandler(object sender, DeleteByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int DeleteByIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteByIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetByIdCompletedEventHandler(object sender, GetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuizResultDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuizResultDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetByGuidCompletedEventHandler(object sender, GetByGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuizResultDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuizResultDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuizResultDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuizResultDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveAllCompletedEventHandler(object sender, SaveAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QuizResultSaveAllDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QuizResultSaveAllDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591