ALTER TABLE SubModuleCategory ALTER COLUMN lmsCourseId NVARCHAR (50) NULL;
UPDATE SubModuleCategory SET lmsCourseId=NULL WHERE lmsCourseId='0';
ALTER TABLE LmsCourseMeeting ALTER COLUMN courseId NVARCHAR (50) NOT NULL;
ALTER TABLE LmsUserParameters ALTER COLUMN course NVARCHAR (50) NOT NULL;
ALTER TABLE LmsUserSession ALTER COLUMN lmsCourseId NVARCHAR (50) NOT NULL;
