// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using EdugameCloud.MVC;
namespace EdugameCloud.MVC.Controllers
{
    public partial class BuildDeliverController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BuildDeliverController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetFile()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Public()
        {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Public);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BuildDeliverController Actions { get { return EdugameCloudT4.BuildDeliver; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "BuildDeliver";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "BuildDeliver";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetFile = "GetFile";
            public readonly string Public = "Public";
            public readonly string GetPublicBuild = "GetPublicBuild";
            public readonly string GetMobileBuild = "GetMobileBuild";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetFile = "GetFile";
            public const string Public = "Public";
            public const string GetPublicBuild = "GetPublicBuild";
            public const string GetMobileBuild = "GetMobileBuild";
        }


        static readonly ActionParamsClass_GetFile s_params_GetFile = new ActionParamsClass_GetFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFile GetFileParams { get { return s_params_GetFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFile
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Public s_params_Public = new ActionParamsClass_Public();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Public PublicParams { get { return s_params_Public; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Public
        {
            public readonly string fileName = "fileName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BuildDeliverController : EdugameCloud.MVC.Controllers.BuildDeliverController
    {
        public T4MVC_BuildDeliverController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult GetFile(string id)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Public(string fileName)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Public);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileName", fileName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetPublicBuild()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetPublicBuild);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetMobileBuild()
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetMobileBuild);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
